### ISSUE TITLE
Duplication of test conditions - possible removal of the test_suite component

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh/refget-compliance-suite#14]
We have the same set of tests being run in two different locations. The first is the compliance report tests in `compliance_suite` and uses the custom built test framework for the compliance report to do its testing. The second set are in `test_suite` and uses Python's `assert` method to do its testing. 

Having the same tests in two locations means changes to one set of tests are not replicated in the other set and could result in divergence. If they cannot be reconciled then docs need to make it clear that these two test sets need to be edited.

**Comment by someshchaturvedi** [comment]
So test_suite was developed during first evaluation and is basically a pass/fail types but compliance suite contains the report system. I think having report system in place we dont really need the test_suite (pytest test suite).

**Comment by andrewyatz** [comment]
Okay :). I've renamed this to possible removal of the test suite. Please don't worry about fixing this as they won't affect your GSOC grading
