### ISSUE TITLE
test_suite/test_sequence_error.py tests too many error conditions in a single statement

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh/refget-compliance-suite#16]
`test_suite/test_sequence_error.py` sometimes tests two error conditions within the same statement. This means there is a race condition dependent on server implementation as to which error code is returned. Specifically:

```python
# First condition
(['6681ac2f62509cfc220d78751b8dc524', '?start=0&end=abc', {'Accept': 'text/embl'}], 415)

# Second condition
(['6681ac2f62509cfc220d78751b8dc524', '?start=0&end=20', {'Accept': 'text/embl', 'Range':'bytes=0-20'}], 415)
```

Assumes that a server will first decide that the `text/embl` MIME type is incorrect and return a `415` rather than setting `end=abc`. The second condition also assumes that MIME detection is done before returning an error about `start=0&end=20` and `Range: bytes=0-20` are used.

Each test should only check one error condition and leave it up to a server implementation as to how it deciphers that we have given it a badly formatted request.

**Comment by someshchaturvedi** [comment]
As per written in the compliance docs. ID not found and unsupported media type are first line of checks. 
[here](https://compliancedoc.readthedocs.io/en/latest/GET_sequence_API/errors/) under generic errors

**Comment by andrewyatz** [comment]
That's fine but I don't see how we can enforce this. For example the framework I have developed the Perl implementation under delays evaluation of the MIME type as the last thing to do. Also we don't say in the spec that there is an order to resolution of errors just "if you do X wrong, Y will be the error"

Please don't worry about addressing this issue as it won't affect your GSOC grading
