### ISSUE TITLE
Clarification on test_suite/*py tests

### ISSUE THREAD

**Issue by yash-puligundla** [ga4gh/refget-compliance-suite#26]
Hi Andy @andrewyatz, 
Could you please help me understand what the tests in test_suite are supposed to do/ their expected behavior?
Thank you!

**Comment by andrewyatz** [comment]
They are meant to test the tests on a mock server for refget. I think it's a bit like who watches the watchmen in a way. They might not be the right type of test to run. Does that answer your question?

**Comment by jb-adams** [comment]
Is it safe to say that the `test_suite` package is the unit/e2e tests for the `refget-compliance-suite` app?

**Comment by andrewyatz** [comment]
Yes perfect @jb-adams

**Comment by yash-puligundla** [comment]
Thanks a lot for confirming @andrewyatz and @jb-adams 
Yes, that answers my question.
