### ISSUE TITLE
Compliance document states 206 for full length sequence retrieval by range

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh/refget-compliance-suite#9]
Going through https://compliancedoc.readthedocs.io/en/latest/GET_sequence_API/success/#sub-sequence-queries and `case 2` we perform a request such as:

```
GET /sequence/681ac2f62509cfc220d78751b8dc524/
Range: bytes=0-230217

GET /sequence/681ac2f62509cfc220d78751b8dc524/
Range: bytes=0-999999999
```

This expects a `206` response back. However the [specification](https://github.com/samtools/hts-specs/blob/master/refget.md#response) states the following

```
On success and either a whole sequence or sub-sequence is returned the server 
shall issue a 200 status code if the entire sequence is returned or 206 if a 
sub-sequence is returned via a Range header.
```

I don't see why a range request means a `206` response. It seems that a server should be allowed to return `200` if the requested sequence was a full length sequence or `206` if it were a partial sequence.

If this is the case then the compliance document and tests need to change to allow this

**Comment by someshchaturvedi** [comment]
200 was there from the beginning but as per the discussion with Matthew on slack, every range header query should return 206

**Comment by andrewyatz** [comment]
I don't have the same interpretation as yourself. I think waiting for @lairdm to comment on this is best. If 206 should be returned on all Range based queries then it should be made more explicit in the specification.

Please don't worry about resolving this as they won't affect your GSOC grading

**Comment by andrewyatz** [comment]
@lairdm I think I need you to chime in on this. Should every range header include a 206 response? Even if it was the whole sequence?
